apiVersion: apps/v1
kind: Deployment
metadata: 
  name: aravind-dep 
  
spec:
  replicas: 4
  
  selector:
    matchLabels:
      app: aravind-app
  template:
    metadata:
      labels:
        app: aravind-app
    spec: 
      tolerations:
        - key: "env"
          operator: "Equal"
          value: "prod"
          effect: "NoSchedule"
      containers:
        - name: flower-cont 
          image: aravindroy1/flower-img:latest
          ports:
            - containerPort: 3015
            